local set = vim.opt

set.backspace = vim.list_extend(vim.opt.backspace:get(), { "nostop" })
set.breakindent = true
set.clipboard = "unnamedplus"
set.cmdheight = 0
set.completeopt = { "menu", "menuone", "noselect" }
set.confirm = true
set.copyindent = true
set.cursorline = true
set.diffopt = vim.list_extend(vim.opt.diffopt:get(), { "algorithm:histogram", "linematch:60" })
set.expandtab = true
set.fillchars = { eob = " " }
set.foldlevel = 99
set.foldlevelstart = 99
set.ignorecase = true
set.infercase = true
set.jumpoptions = {}
set.laststatus = 3
set.linebreak = true
set.mouse = "a"
set.number = true
set.preserveindent = true
set.pumheight = 10
set.relativenumber = true
set.shiftround = true
set.shiftwidth = 0
set.shortmess = vim.tbl_deep_extend("force", vim.opt.shortmess:get(), { s = true, I = true })
set.showtabline = 2
set.signcolumn = "yes"
set.smartcase = true
set.tabstop = 2
set.termguicolors = true
set.timeoutlen = 500
set.title = true
set.undofile = true
set.updatetime = 300
set.virtualedit = "block"
set.wrap = false
set.writebackup = false
