"$schema" = "https://starship.rs/config-schema.json"

palette = "nord"

right_format = """$git_branch$git_commit$git_state$git_metrics$git_status"""

[directory]
style = "white"
format = "[$path ](bold $style)"
repo_root_style = "dark_blue"

[git_branch]
style = "gray"
format = "[on](white) [$symbol$branch ]($style)"

[git_status]
style = "fg:red"
untracked = "[~$count](bold green)"
staged = "[$count](bold green)"
stashed = "[$$count](teal)"
deleted = "[$count](bold red)"
modified = "[!$count](bold yellow)"
ahead = "[$count](bold purple)"
behind = "[$count](bold purple)"
diverged = "[$ahead_count$behind_count](bold purple)"
format = "([$all_status$ahead_behind]($style) )"

[shell]
disabled = false

[palettes.nord]
dark_blue = "#61afef"
blue = "#81a1c1"
teal = "#88c0d0"
red = "#bf616a"
orange = "#d08770"
green = "#a3be8c"
yellow = "#ebcb8b"
purple = "#b48ead"
# gray = "#545d6f"
gray = "#60728a"
black = "#2e3440"
white = "#d8dee9"
