-- local ok, ls = pcall(require, "luasnip")
-- if not ok then
--   return
-- end
--
-- ls.add_snippets("javascript", {
--   ls.snippet("cl", {
--     ls.text_node("console.log("),
--     ls.function_node(function (_, snip)
--       return snip.env.SELECT_RAW or ""
--     end),
--     ls.text_node(");")
--   })
-- })
